### PR TITLE
Lsync react

### PR DESCRIPTION
**Pull request by IanWorley**

### CODE REVIEW

**Comment by quadcom** [comment]
@IanWorley - are you building Docker images including your mods?

It appears that the original author of SS has abandoned the project. I've reached out to them a couple of times, but there's been no reply. Some outstanding issues pop up now and then, as well as a bunch of FR posts from people. It would be great if someone took over the helm of this ship and ran with it.

If I was more skilled in code I would have done so myself but alas, it's well outside my expertise. I have tried to help out answering questions when I can over the years as I really appreciated the project. It' the only one of it's kind and works better than anything else out there for this purpose.

**Comment by IanWorley** [comment]
@quadcom I intend to build docker images with my mods. I would like to maintain my own fork  as I agree with you there is not any other great alternative which has been disappointing. I hate to ask because I haven't made a lot of images myself but I took a peek at your fork are you actually running the lastest base image of ubuntu with seedsync?

**Comment by quadcom** [comment]
Yes, that's the master build code still. I've made no changes to it.

I'm running my SS on UnRaid at the moment.

I used to have an ESXi box running Ubuntu, I think v21, and it was running fine. 

I forked it because I was going to try to learn some coding skills using this project as a motivator. Too much life got in the way though and couldn't spend the time. Besides, I don't think trying to learn something using someone else's code is probably not the best approach, especially when starting from scratch.

**Comment by quadcom** [comment]
I looked into building images, and it doesn't seem too difficult—but I've been caught in that trap before, lol.

I'm sure we could figure that out. Unless someone else happens by and has some expertise in that!

**Comment by timrettop** [comment]
@IanWorley I came across this project and noticed the state.  Have you come back to trying to revitalize this?

**Comment by IanWorley** [comment]
@timrettop  As of yet I have not right now I have been busy dealing with school and working 40 hours week. Today I just finish all my school work for the summer term. Right now I would rather work on a personal project than this so you can take a stab at it :).

**Comment by IanWorley** [comment]
for right now I will nuke my current fork

**Comment by JshGrn** [comment]
@IanWorley if you end up working on this project I am happy to support you, I cannot work out why lftp timeout and parser issues, instead I am falling back to lftp shell script which without the GUI is not ideal!

would pay for functional stable software like this

**Pull request closed without merging**
